"""
Phase 5 — Report.

Writes output/digest_<date>.md for human review: this run's top patterns, the
per-listing drafts ready for approval, and (if not the first run) what changed
since last time. Prints the file path and estimated token spend.

Standalone debug:  python -m phases.p5_report [run_id]
"""

import datetime as dt
import json
import os

import config
import db


def _fetch(run_id):
    with db.get_conn() as conn:
        run = conn.execute(
            "SELECT * FROM runs WHERE run_id = ?", (run_id,)
        ).fetchone()
        report = conn.execute(
            "SELECT * FROM pattern_reports WHERE run_id = ? "
            "ORDER BY id DESC LIMIT 1",
            (run_id,),
        ).fetchone()
        drafts = conn.execute(
            "SELECT * FROM drafts WHERE run_id = ? ORDER BY listing_address, platform",
            (run_id,),
        ).fetchall()
        n_posts = conn.execute(
            "SELECT COUNT(*) FROM posts WHERE run_id = ?", (run_id,)
        ).fetchone()[0]
    return run, report, drafts, n_posts


def _patterns_md(report):
    if not report:
        return "_No pattern report._"
    patterns = json.loads(report["report_json"]).get("patterns", {})
    lines = [f"Studied **{report['posts_studied']}** top post(s).", ""]
    lines.append("| Field | Dominant | Distribution |")
    lines.append("|---|---|---|")
    for field, info in patterns.items():
        dist = ", ".join(f"{k} ({v})" for k, v in info.get("distribution", {}).items())
        lines.append(f"| {field} | `{info.get('dominant')}` | {dist or '—'} |")
    return "\n".join(lines)


def _drafts_md(drafts):
    if not drafts:
        return ("_No drafts generated. Phase 3 needs a real ANTHROPIC_API_KEY "
                "(Sonnet) — set it in `.env` and re-run._")
    by_listing = {}
    for d in drafts:
        by_listing.setdefault(d["listing_address"], []).append(d)

    out = []
    for address, items in by_listing.items():
        out.append(f"### 🏠 {address}\n")
        for d in items:
            hashtags = d["hashtags"] or ""
            outline = (d["video_outline"] or "").strip()
            outline_md = "\n".join(
                f"  {i}. {ln}" for i, ln in enumerate(outline.splitlines(), 1)
            ) if outline else "  _(none)_"
            out.append(
                f"<details>\n<summary><b>{d['platform']}</b> — "
                f"{d['suggested_format'] or 'format n/a'}</summary>\n\n"
                f"**Hook:** {d['hook']}\n\n"
                f"**Caption:**\n\n{d['caption']}\n\n"
                f"**Hashtags:** {hashtags}\n\n"
                f"**Short-video outline:**\n{outline_md}\n\n"
                f"</details>\n"
            )
        out.append("")
    return "\n".join(out)


def report(run_id: str, compare_md: str = "") -> str:
    """Write the markdown digest, return its file path."""
    run, rpt, drafts, n_posts = _fetch(run_id)
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    date = dt.date.today().isoformat()
    path = os.path.join(config.OUTPUT_DIR, f"digest_{date}.md")

    in_tok = run["est_input_tokens"] if run else 0
    out_tok = run["est_output_tokens"] if run else 0
    cost = run["est_cost_usd"] if run else 0.0

    md = f"""# Content Digest — {date}

**Run:** `{run_id}`
**Market:** {config.MARKET_LABEL}
**Collected:** {n_posts} posts (cap {config.MAX_POSTS_PER_RUN})
**Estimated Claude spend this run:** ~${cost:.4f}  ({in_tok:,} in / {out_tok:,} out tokens)

> ⚠️ Drafts are for **Sri's manual review and approval**. Nothing is auto-posted.
> Verify all listing facts before publishing.

---

## 1. Top patterns this run

{_patterns_md(rpt)}

---

## 2. Approval-ready drafts

{_drafts_md(drafts)}

---

## 3. What changed since last run

{compare_md or "_Comparison not run._"}

---

_Generated by the Real Estate Content Agent PoC — study → apply loop._
"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(md)

    print(f"[p5] digest written -> {path}")
    print(f"[p5] estimated spend this run: ~${cost:.4f} "
          f"({in_tok:,} in / {out_tok:,} out tokens)")
    return path


if __name__ == "__main__":
    import sys
    from phases import p4_compare

    rid = sys.argv[1] if len(sys.argv) > 1 else None
    if not rid:
        with db.get_conn() as conn:
            row = conn.execute(
                "SELECT run_id FROM runs ORDER BY started_at DESC LIMIT 1"
            ).fetchone()
            rid = row["run_id"] if row else "none"
    report(rid, p4_compare.compare(rid))
